import joi  from 'joi'
export const email = joi.string().pattern(new RegExp('gmail.com$')).required()
export const avatar  = joi.string().required()
export const maToaNha = joi.string().required()
export const tenToaNha = joi.string().required()
export const title = joi.string().required()
export const name = joi.string().required()
export const soTang = joi.number().required()
export const maGiuong = joi.string().required()
export const maPhong = joi.string().required()
export const viTriGiuong = joi.number().required()
export const maSV = joi.string().required()
export const hoTen = joi.string().required()
export const soCMND = joi.string().required()
export const ngaySinh = joi.date().required()
export const soDienThoai = joi.string().required()
export const noiSinh = joi.string().required()
export const diaChiThuongTru = joi.string().required()
export const tenTruong = joi.string().required()
export const namVaoTruong = joi.string().required()
export const gioiTinh= joi.string().required()
export const bid  = joi.string().required()
export const tenPhong  = joi.string().required()
export const bids  = joi.array().required()
export const gioiTinhSV= joi.string().required()
export const hinhThucThanhToan  = joi.string().required()
export const donGia  = joi.number().required()
export const soNguoiToiDa  = joi.number().required()
export const viTriTang  = joi.number().required()
export const filename = joi.array().required()


